version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: smart-helpdesk-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: smart_helpdesk
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - smart-helpdesk-network

  redis:
    image: redis:7.2-alpine
    container_name: smart-helpdesk-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - smart-helpdesk-network

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: smart-helpdesk-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/smart_helpdesk?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 24h
      GEMINI_API_KEY: your-gemini-api-key
      EMAIL_SERVICE_URL: http://localhost:8080
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - smart-helpdesk-network
    develop:
      watch:
        - action: sync
          path: ./server/src
          target: /app/src
        - action: rebuild
          path: ./server/package.json

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: smart-helpdesk-client
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
      VITE_WS_URL: ws://localhost:3000
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - smart-helpdesk-network
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: /app/src
        - action: rebuild
          path: ./client/package.json

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  smart-helpdesk-network:
    driver: bridge